const FETCH_DATA_START = 'FETCH_DATA_START';
const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
const SET_ACTIVE_COUNTRY = 'SET_ACTIVE_COUNTRY';
const FETCH_HISTORICAL_DATA_COUNTRY_SUCCESS = 'FETCH_HISTORICAL_DATA_COUNTRY_SUCCESS';
const FETCH_HISTORICAL_DATA_COUNTRY_START = 'FETCH_HISTORICAL_DATA_COUNTRY_START';
const FETCH_HISTORICAL_DATA_COUNTRY_ERROR = 'FETCH_HISTORICAL_DATA_COUNTRY_ERROR';

export {
  FETCH_DATA_START,
  FETCH_DATA_SUCCESS,
  FETCH_DATA_ERROR,
  SET_ACTIVE_COUNTRY,
  FETCH_HISTORICAL_DATA_COUNTRY_SUCCESS,
  FETCH_HISTORICAL_DATA_COUNTRY_START,
  FETCH_HISTORICAL_DATA_COUNTRY_ERROR
}
